# Generated by Django 6.0.7 on 2026-07-12 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('project_link', models.URLField(blank=True, max_length=500, null=True)),
                ('abstract', models.TextField(help_text='The raw or cleaned project description.')),
                ('predicted_track', models.CharField(blank=True, max_length=100, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='How confident the ML model is (0.0 to 1.0)')),
                ('is_reviewed', models.BooleanField(default=False, help_text='Has an organizer manually verified this?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
