# Generated by Django 5.2 on 2026-07-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='score',
            field=models.IntegerField(default=0, help_text="Judge's score out of 100"),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
