# Generated by Django 5.2 on 2026-07-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_projectsubmission_score_alter_projectsubmission_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='score',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='github_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
