# Generated by Django 5.2 on 2026-07-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_remove_projectsubmission_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectsubmission',
            name='github_status',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='github_url',
        ),
        migrations.RemoveField(
            model_name='projectsubmission',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='score',
            field=models.IntegerField(default=0, help_text='Manual score given by the judge (0-100)'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='target_track',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
