# Generated by Django 5.2 on 2026-07-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_remove_projectsubmission_github_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='github_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='tech_stack',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
